spring:
  application:
    name: discovery

server:
  port: 8761

logging:
  level:
    root: DEBUG
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

