spring:
  application:
    name: admin

server:
  port: 8762

logging:
  level:
    root: DEBUG
    com:
      netflix:
        discovery: 'OFF'
        eureka: 'OFF'
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true

# ACTUATOR
management:
  endpoints:
    web:
      exposure:
        include: '*'

